#!/bin/sh
commit_msg=$(cat "$1")

if ! echo "$commit_msg" | grep -qE "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\\([a-zA-Z]+\\))?!?: .{1,72}$"; then
  echo "Invalid commit message format."
  echo "Commit message should follow the conventional commit format:"
  echo "<type>(<scope>): <subject>"
  echo "Available type: feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"
  echo "Example: feat(auth): add login functionality"
  exit 1
fi
